//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: packets.proto

package com.github.fernthedev.packets.proto;

@kotlin.jvm.JvmName("-initializeclientWorldUpdatePacket")
public inline fun clientWorldUpdatePacket(block: com.github.fernthedev.packets.proto.ClientWorldUpdatePacketKt.Dsl.() -> kotlin.Unit): com.github.fernthedev.packets.proto.Packets.ClientWorldUpdatePacket =
  com.github.fernthedev.packets.proto.ClientWorldUpdatePacketKt.Dsl._create(com.github.fernthedev.packets.proto.Packets.ClientWorldUpdatePacket.newBuilder()).apply { block() }._build()
public object ClientWorldUpdatePacketKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.github.fernthedev.packets.proto.Packets.ClientWorldUpdatePacket.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.github.fernthedev.packets.proto.Packets.ClientWorldUpdatePacket.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.github.fernthedev.packets.proto.Packets.ClientWorldUpdatePacket = _builder.build()

    /**
     * <code>.com.github.fernthedev.packets.proto.GameObject playerObject = 1;</code>
     */
    public var playerObject: com.github.fernthedev.packets.proto.Packets.GameObject
      @JvmName("getPlayerObject")
      get() = _builder.getPlayerObject()
      @JvmName("setPlayerObject")
      set(value) {
        _builder.setPlayerObject(value)
      }
    /**
     * <code>.com.github.fernthedev.packets.proto.GameObject playerObject = 1;</code>
     */
    public fun clearPlayerObject() {
      _builder.clearPlayerObject()
    }
    /**
     * <code>.com.github.fernthedev.packets.proto.GameObject playerObject = 1;</code>
     * @return Whether the playerObject field is set.
     */
    public fun hasPlayerObject(): kotlin.Boolean {
      return _builder.hasPlayerObject()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EntitiesHashCodeMapProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * nullable 
     * </pre>
     *
     * <code>map&lt;string, int32&gt; entitiesHashCodeMap = 2;</code>
     */
     public val entitiesHashCodeMap: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, EntitiesHashCodeMapProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getEntitiesHashCodeMapMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getEntitiesHashCodeMapMap()
      )
    /**
     * <pre>
     * nullable 
     * </pre>
     *
     * <code>map&lt;string, int32&gt; entitiesHashCodeMap = 2;</code>
     */
    @JvmName("putEntitiesHashCodeMap")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, EntitiesHashCodeMapProxy>
      .put(key: kotlin.String, value: kotlin.Int) {
         _builder.putEntitiesHashCodeMap(key, value)
       }
    /**
     * <pre>
     * nullable 
     * </pre>
     *
     * <code>map&lt;string, int32&gt; entitiesHashCodeMap = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setEntitiesHashCodeMap")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, EntitiesHashCodeMapProxy>
      .set(key: kotlin.String, value: kotlin.Int) {
         put(key, value)
       }
    /**
     * <pre>
     * nullable 
     * </pre>
     *
     * <code>map&lt;string, int32&gt; entitiesHashCodeMap = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeEntitiesHashCodeMap")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, EntitiesHashCodeMapProxy>
      .remove(key: kotlin.String) {
         _builder.removeEntitiesHashCodeMap(key)
       }
    /**
     * <pre>
     * nullable 
     * </pre>
     *
     * <code>map&lt;string, int32&gt; entitiesHashCodeMap = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllEntitiesHashCodeMap")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, EntitiesHashCodeMapProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.Int>) {
         _builder.putAllEntitiesHashCodeMap(map)
       }
    /**
     * <pre>
     * nullable 
     * </pre>
     *
     * <code>map&lt;string, int32&gt; entitiesHashCodeMap = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearEntitiesHashCodeMap")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, EntitiesHashCodeMapProxy>
      .clear() {
         _builder.clearEntitiesHashCodeMap()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.github.fernthedev.packets.proto.Packets.ClientWorldUpdatePacket.copy(block: com.github.fernthedev.packets.proto.ClientWorldUpdatePacketKt.Dsl.() -> kotlin.Unit): com.github.fernthedev.packets.proto.Packets.ClientWorldUpdatePacket =
  com.github.fernthedev.packets.proto.ClientWorldUpdatePacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val com.github.fernthedev.packets.proto.Packets.ClientWorldUpdatePacketOrBuilder.playerObjectOrNull: com.github.fernthedev.packets.proto.Packets.GameObject?
  get() = if (hasPlayerObject()) getPlayerObject() else null

