//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: packets.proto

package com.github.fernthedev.packets.proto;

@kotlin.jvm.JvmName("-initializegameObjectNullable")
public inline fun gameObjectNullable(block: com.github.fernthedev.packets.proto.GameObjectNullableKt.Dsl.() -> kotlin.Unit): com.github.fernthedev.packets.proto.Packets.GameObjectNullable =
  com.github.fernthedev.packets.proto.GameObjectNullableKt.Dsl._create(com.github.fernthedev.packets.proto.Packets.GameObjectNullable.newBuilder()).apply { block() }._build()
public object GameObjectNullableKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.github.fernthedev.packets.proto.Packets.GameObjectNullable.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.github.fernthedev.packets.proto.Packets.GameObjectNullable.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.github.fernthedev.packets.proto.Packets.GameObjectNullable = _builder.build()

    /**
     * <code>.com.github.fernthedev.packets.proto.GameObject o = 1;</code>
     */
    public var o: com.github.fernthedev.packets.proto.Packets.GameObject
      @JvmName("getO")
      get() = _builder.getO()
      @JvmName("setO")
      set(value) {
        _builder.setO(value)
      }
    /**
     * <code>.com.github.fernthedev.packets.proto.GameObject o = 1;</code>
     */
    public fun clearO() {
      _builder.clearO()
    }
    /**
     * <code>.com.github.fernthedev.packets.proto.GameObject o = 1;</code>
     * @return Whether the o field is set.
     */
    public fun hasO(): kotlin.Boolean {
      return _builder.hasO()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.github.fernthedev.packets.proto.Packets.GameObjectNullable.copy(block: com.github.fernthedev.packets.proto.GameObjectNullableKt.Dsl.() -> kotlin.Unit): com.github.fernthedev.packets.proto.Packets.GameObjectNullable =
  com.github.fernthedev.packets.proto.GameObjectNullableKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val com.github.fernthedev.packets.proto.Packets.GameObjectNullableOrBuilder.oOrNull: com.github.fernthedev.packets.proto.Packets.GameObject?
  get() = if (hasO()) getO() else null

