//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: packets.proto

package com.github.fernthedev.packets.proto;

@kotlin.jvm.JvmName("-initializelocation")
public inline fun location(block: com.github.fernthedev.packets.proto.LocationKt.Dsl.() -> kotlin.Unit): com.github.fernthedev.packets.proto.Packets.Location =
  com.github.fernthedev.packets.proto.LocationKt.Dsl._create(com.github.fernthedev.packets.proto.Packets.Location.newBuilder()).apply { block() }._build()
public object LocationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.github.fernthedev.packets.proto.Packets.Location.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.github.fernthedev.packets.proto.Packets.Location.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.github.fernthedev.packets.proto.Packets.Location = _builder.build()

    /**
     * <code>float x = 1;</code>
     */
    public var x: kotlin.Float
      @JvmName("getX")
      get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * <code>float x = 1;</code>
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * <code>float y = 2;</code>
     */
    public var y: kotlin.Float
      @JvmName("getY")
      get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * <code>float y = 2;</code>
     */
    public fun clearY() {
      _builder.clearY()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.github.fernthedev.packets.proto.Packets.Location.copy(block: com.github.fernthedev.packets.proto.LocationKt.Dsl.() -> kotlin.Unit): com.github.fernthedev.packets.proto.Packets.Location =
  com.github.fernthedev.packets.proto.LocationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

