//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: packets.proto

package com.github.fernthedev.packets.proto;

@kotlin.jvm.JvmName("-initializeuUID")
public inline fun uUID(block: com.github.fernthedev.packets.proto.UUIDKt.Dsl.() -> kotlin.Unit): com.github.fernthedev.packets.proto.Packets.UUID =
  com.github.fernthedev.packets.proto.UUIDKt.Dsl._create(com.github.fernthedev.packets.proto.Packets.UUID.newBuilder()).apply { block() }._build()
public object UUIDKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.github.fernthedev.packets.proto.Packets.UUID.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.github.fernthedev.packets.proto.Packets.UUID.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.github.fernthedev.packets.proto.Packets.UUID = _builder.build()

    /**
     * <code>bytes value = 1;</code>
     */
    public var value: com.google.protobuf.ByteString
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * <code>bytes value = 1;</code>
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.github.fernthedev.packets.proto.Packets.UUID.copy(block: com.github.fernthedev.packets.proto.UUIDKt.Dsl.() -> kotlin.Unit): com.github.fernthedev.packets.proto.Packets.UUID =
  com.github.fernthedev.packets.proto.UUIDKt.Dsl._create(this.toBuilder()).apply { block() }._build()

